// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Upload config request
type UploadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // Config content
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                        // "json", "yaml", "toml"
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // User/system uploading
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`              // Optional description
	Validate      bool                   `protobuf:"varint,6,opt,name=validate,proto3" json:"validate,omitempty"`                   // Validate before upload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigRequest) Reset() {
	*x = UploadConfigRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigRequest) ProtoMessage() {}

func (x *UploadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigRequest.ProtoReflect.Descriptor instead.
func (*UploadConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *UploadConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UploadConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UploadConfigRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UploadConfigRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UploadConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadConfigRequest) GetValidate() bool {
	if x != nil {
		return x.Validate
	}
	return false
}

type UploadConfigResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfigId         string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Version          int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Success          bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ValidationErrors []string               `protobuf:"bytes,5,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadConfigResponse) Reset() {
	*x = UploadConfigResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigResponse) ProtoMessage() {}

func (x *UploadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigResponse.ProtoReflect.Descriptor instead.
func (*UploadConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *UploadConfigResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *UploadConfigResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UploadConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadConfigResponse) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

// Get config request
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigData            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigResponse) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List configs request
type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // Max results
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListConfigsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListConfigsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConfigsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigMetadata      `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListConfigsResponse) GetConfigs() []*ConfigMetadata {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListConfigsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListConfigsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Delete config request
type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConfigRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Start rollout request
type StartRolloutRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfigId         string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Strategy         RolloutStrategy        `protobuf:"varint,2,opt,name=strategy,proto3,enum=configservice.RolloutStrategy" json:"strategy,omitempty"`
	TargetPercentage int32                  `protobuf:"varint,3,opt,name=target_percentage,json=targetPercentage,proto3" json:"target_percentage,omitempty"` // For PERCENTAGE strategy
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartRolloutRequest) Reset() {
	*x = StartRolloutRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRolloutRequest) ProtoMessage() {}

func (x *StartRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRolloutRequest.ProtoReflect.Descriptor instead.
func (*StartRolloutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *StartRolloutRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *StartRolloutRequest) GetStrategy() RolloutStrategy {
	if x != nil {
		return x.Strategy
	}
	return RolloutStrategy_ALL_AT_ONCE
}

func (x *StartRolloutRequest) GetTargetPercentage() int32 {
	if x != nil {
		return x.TargetPercentage
	}
	return 0
}

type StartRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RolloutId     string                 `protobuf:"bytes,3,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRolloutResponse) Reset() {
	*x = StartRolloutResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRolloutResponse) ProtoMessage() {}

func (x *StartRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRolloutResponse.ProtoReflect.Descriptor instead.
func (*StartRolloutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *StartRolloutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRolloutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartRolloutResponse) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

// Get rollout status request
type GetRolloutStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolloutStatusRequest) Reset() {
	*x = GetRolloutStatusRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolloutStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolloutStatusRequest) ProtoMessage() {}

func (x *GetRolloutStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolloutStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRolloutStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetRolloutStatusRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type GetRolloutStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutState  *RolloutState          `protobuf:"bytes,1,opt,name=rollout_state,json=rolloutState,proto3" json:"rollout_state,omitempty"`
	Instances     []*ServiceInstance     `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"` // Instances affected
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolloutStatusResponse) Reset() {
	*x = GetRolloutStatusResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolloutStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolloutStatusResponse) ProtoMessage() {}

func (x *GetRolloutStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolloutStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRolloutStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetRolloutStatusResponse) GetRolloutState() *RolloutState {
	if x != nil {
		return x.RolloutState
	}
	return nil
}

func (x *GetRolloutStatusResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *GetRolloutStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Rollback request
type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TargetVersion int64                  `protobuf:"varint,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"` // Version to rollback to (0 = previous)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RollbackRequest) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConfigId      string                 `protobuf:"bytes,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\rconfigservice\x1a\fconfig.proto\"\xc7\x01\n" +
	"\x13UploadConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bvalidate\x18\x06 \x01(\bR\bvalidate\"\xae\x01\n" +
	"\x14UploadConfigResponse\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12+\n" +
	"\x11validation_errors\x18\x05 \x03(\tR\x10validationErrors\"/\n" +
	"\x10GetConfigRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\"z\n" +
	"\x11GetConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.configservice.ConfigDataR\x06config\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"e\n" +
	"\x12ListConfigsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x89\x01\n" +
	"\x13ListConfigsResponse\x127\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1d.configservice.ConfigMetadataR\aconfigs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"2\n" +
	"\x13DeleteConfigRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\"J\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x13StartRolloutRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12:\n" +
	"\bstrategy\x18\x02 \x01(\x0e2\x1e.configservice.RolloutStrategyR\bstrategy\x12+\n" +
	"\x11target_percentage\x18\x03 \x01(\x05R\x10targetPercentage\"i\n" +
	"\x14StartRolloutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x03 \x01(\tR\trolloutId\"6\n" +
	"\x17GetRolloutStatusRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\"\xb4\x01\n" +
	"\x18GetRolloutStatusResponse\x12@\n" +
	"\rrollout_state\x18\x01 \x01(\v2\x1b.configservice.RolloutStateR\frolloutState\x12<\n" +
	"\tinstances\x18\x02 \x03(\v2\x1e.configservice.ServiceInstanceR\tinstances\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"[\n" +
	"\x0fRollbackRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\x03R\rtargetVersion\"c\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\tR\bconfigId2\xf5\x04\n" +
	"\x10ConfigAPIService\x12W\n" +
	"\fUploadConfig\x12\".configservice.UploadConfigRequest\x1a#.configservice.UploadConfigResponse\x12N\n" +
	"\tGetConfig\x12\x1f.configservice.GetConfigRequest\x1a .configservice.GetConfigResponse\x12T\n" +
	"\vListConfigs\x12!.configservice.ListConfigsRequest\x1a\".configservice.ListConfigsResponse\x12W\n" +
	"\fDeleteConfig\x12\".configservice.DeleteConfigRequest\x1a#.configservice.DeleteConfigResponse\x12W\n" +
	"\fStartRollout\x12\".configservice.StartRolloutRequest\x1a#.configservice.StartRolloutResponse\x12c\n" +
	"\x10GetRolloutStatus\x12&.configservice.GetRolloutStatusRequest\x1a'.configservice.GetRolloutStatusResponse\x12K\n" +
	"\bRollback\x12\x1e.configservice.RollbackRequest\x1a\x1f.configservice.RollbackResponseB#Z!github.com/codec404/Konfig/pkg/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_goTypes = []any{
	(*UploadConfigRequest)(nil),      // 0: configservice.UploadConfigRequest
	(*UploadConfigResponse)(nil),     // 1: configservice.UploadConfigResponse
	(*GetConfigRequest)(nil),         // 2: configservice.GetConfigRequest
	(*GetConfigResponse)(nil),        // 3: configservice.GetConfigResponse
	(*ListConfigsRequest)(nil),       // 4: configservice.ListConfigsRequest
	(*ListConfigsResponse)(nil),      // 5: configservice.ListConfigsResponse
	(*DeleteConfigRequest)(nil),      // 6: configservice.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),     // 7: configservice.DeleteConfigResponse
	(*StartRolloutRequest)(nil),      // 8: configservice.StartRolloutRequest
	(*StartRolloutResponse)(nil),     // 9: configservice.StartRolloutResponse
	(*GetRolloutStatusRequest)(nil),  // 10: configservice.GetRolloutStatusRequest
	(*GetRolloutStatusResponse)(nil), // 11: configservice.GetRolloutStatusResponse
	(*RollbackRequest)(nil),          // 12: configservice.RollbackRequest
	(*RollbackResponse)(nil),         // 13: configservice.RollbackResponse
	(*ConfigData)(nil),               // 14: configservice.ConfigData
	(*ConfigMetadata)(nil),           // 15: configservice.ConfigMetadata
	(RolloutStrategy)(0),             // 16: configservice.RolloutStrategy
	(*RolloutState)(nil),             // 17: configservice.RolloutState
	(*ServiceInstance)(nil),          // 18: configservice.ServiceInstance
}
var file_api_proto_depIdxs = []int32{
	14, // 0: configservice.GetConfigResponse.config:type_name -> configservice.ConfigData
	15, // 1: configservice.ListConfigsResponse.configs:type_name -> configservice.ConfigMetadata
	16, // 2: configservice.StartRolloutRequest.strategy:type_name -> configservice.RolloutStrategy
	17, // 3: configservice.GetRolloutStatusResponse.rollout_state:type_name -> configservice.RolloutState
	18, // 4: configservice.GetRolloutStatusResponse.instances:type_name -> configservice.ServiceInstance
	0,  // 5: configservice.ConfigAPIService.UploadConfig:input_type -> configservice.UploadConfigRequest
	2,  // 6: configservice.ConfigAPIService.GetConfig:input_type -> configservice.GetConfigRequest
	4,  // 7: configservice.ConfigAPIService.ListConfigs:input_type -> configservice.ListConfigsRequest
	6,  // 8: configservice.ConfigAPIService.DeleteConfig:input_type -> configservice.DeleteConfigRequest
	8,  // 9: configservice.ConfigAPIService.StartRollout:input_type -> configservice.StartRolloutRequest
	10, // 10: configservice.ConfigAPIService.GetRolloutStatus:input_type -> configservice.GetRolloutStatusRequest
	12, // 11: configservice.ConfigAPIService.Rollback:input_type -> configservice.RollbackRequest
	1,  // 12: configservice.ConfigAPIService.UploadConfig:output_type -> configservice.UploadConfigResponse
	3,  // 13: configservice.ConfigAPIService.GetConfig:output_type -> configservice.GetConfigResponse
	5,  // 14: configservice.ConfigAPIService.ListConfigs:output_type -> configservice.ListConfigsResponse
	7,  // 15: configservice.ConfigAPIService.DeleteConfig:output_type -> configservice.DeleteConfigResponse
	9,  // 16: configservice.ConfigAPIService.StartRollout:output_type -> configservice.StartRolloutResponse
	11, // 17: configservice.ConfigAPIService.GetRolloutStatus:output_type -> configservice.GetRolloutStatusResponse
	13, // 18: configservice.ConfigAPIService.Rollback:output_type -> configservice.RollbackResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
