// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigAPIService_UploadConfig_FullMethodName     = "/configservice.ConfigAPIService/UploadConfig"
	ConfigAPIService_GetConfig_FullMethodName        = "/configservice.ConfigAPIService/GetConfig"
	ConfigAPIService_ListConfigs_FullMethodName      = "/configservice.ConfigAPIService/ListConfigs"
	ConfigAPIService_DeleteConfig_FullMethodName     = "/configservice.ConfigAPIService/DeleteConfig"
	ConfigAPIService_StartRollout_FullMethodName     = "/configservice.ConfigAPIService/StartRollout"
	ConfigAPIService_GetRolloutStatus_FullMethodName = "/configservice.ConfigAPIService/GetRolloutStatus"
	ConfigAPIService_Rollback_FullMethodName         = "/configservice.ConfigAPIService/Rollback"
)

// ConfigAPIServiceClient is the client API for ConfigAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API Service - handles config uploads and management
type ConfigAPIServiceClient interface {
	// Upload a new configuration
	UploadConfig(ctx context.Context, in *UploadConfigRequest, opts ...grpc.CallOption) (*UploadConfigResponse, error)
	// Get configuration by ID
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// List configurations for a service
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
	// Delete a configuration
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	// Start a rollout
	StartRollout(ctx context.Context, in *StartRolloutRequest, opts ...grpc.CallOption) (*StartRolloutResponse, error)
	// Get rollout status
	GetRolloutStatus(ctx context.Context, in *GetRolloutStatusRequest, opts ...grpc.CallOption) (*GetRolloutStatusResponse, error)
	// Rollback to previous version
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
}

type configAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigAPIServiceClient(cc grpc.ClientConnInterface) ConfigAPIServiceClient {
	return &configAPIServiceClient{cc}
}

func (c *configAPIServiceClient) UploadConfig(ctx context.Context, in *UploadConfigRequest, opts ...grpc.CallOption) (*UploadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadConfigResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_UploadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAPIServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAPIServiceClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_ListConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAPIServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAPIServiceClient) StartRollout(ctx context.Context, in *StartRolloutRequest, opts ...grpc.CallOption) (*StartRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRolloutResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_StartRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAPIServiceClient) GetRolloutStatus(ctx context.Context, in *GetRolloutStatusRequest, opts ...grpc.CallOption) (*GetRolloutStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolloutStatusResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_GetRolloutStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAPIServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, ConfigAPIService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigAPIServiceServer is the server API for ConfigAPIService service.
// All implementations must embed UnimplementedConfigAPIServiceServer
// for forward compatibility.
//
// API Service - handles config uploads and management
type ConfigAPIServiceServer interface {
	// Upload a new configuration
	UploadConfig(context.Context, *UploadConfigRequest) (*UploadConfigResponse, error)
	// Get configuration by ID
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// List configurations for a service
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	// Delete a configuration
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	// Start a rollout
	StartRollout(context.Context, *StartRolloutRequest) (*StartRolloutResponse, error)
	// Get rollout status
	GetRolloutStatus(context.Context, *GetRolloutStatusRequest) (*GetRolloutStatusResponse, error)
	// Rollback to previous version
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	mustEmbedUnimplementedConfigAPIServiceServer()
}

// UnimplementedConfigAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigAPIServiceServer struct{}

func (UnimplementedConfigAPIServiceServer) UploadConfig(context.Context, *UploadConfigRequest) (*UploadConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadConfig not implemented")
}
func (UnimplementedConfigAPIServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedConfigAPIServiceServer) ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedConfigAPIServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedConfigAPIServiceServer) StartRollout(context.Context, *StartRolloutRequest) (*StartRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRollout not implemented")
}
func (UnimplementedConfigAPIServiceServer) GetRolloutStatus(context.Context, *GetRolloutStatusRequest) (*GetRolloutStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolloutStatus not implemented")
}
func (UnimplementedConfigAPIServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedConfigAPIServiceServer) mustEmbedUnimplementedConfigAPIServiceServer() {}
func (UnimplementedConfigAPIServiceServer) testEmbeddedByValue()                          {}

// UnsafeConfigAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigAPIServiceServer will
// result in compilation errors.
type UnsafeConfigAPIServiceServer interface {
	mustEmbedUnimplementedConfigAPIServiceServer()
}

func RegisterConfigAPIServiceServer(s grpc.ServiceRegistrar, srv ConfigAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigAPIService_ServiceDesc, srv)
}

func _ConfigAPIService_UploadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).UploadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_UploadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).UploadConfig(ctx, req.(*UploadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAPIService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAPIService_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAPIService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAPIService_StartRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).StartRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_StartRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).StartRollout(ctx, req.(*StartRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAPIService_GetRolloutStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolloutStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).GetRolloutStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_GetRolloutStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).GetRolloutStatus(ctx, req.(*GetRolloutStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAPIService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAPIServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAPIService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAPIServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigAPIService_ServiceDesc is the grpc.ServiceDesc for ConfigAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configservice.ConfigAPIService",
	HandlerType: (*ConfigAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadConfig",
			Handler:    _ConfigAPIService_UploadConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ConfigAPIService_GetConfig_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _ConfigAPIService_ListConfigs_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _ConfigAPIService_DeleteConfig_Handler,
		},
		{
			MethodName: "StartRollout",
			Handler:    _ConfigAPIService_StartRollout_Handler,
		},
		{
			MethodName: "GetRolloutStatus",
			Handler:    _ConfigAPIService_GetRolloutStatus_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _ConfigAPIService_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
