// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: config.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rollout strategy
type RolloutStrategy int32

const (
	RolloutStrategy_ALL_AT_ONCE RolloutStrategy = 0 // Push to all instances immediately
	RolloutStrategy_CANARY      RolloutStrategy = 1 // Push to small percentage first
	RolloutStrategy_PERCENTAGE  RolloutStrategy = 2 // Gradual percentage-based rollout
)

// Enum value maps for RolloutStrategy.
var (
	RolloutStrategy_name = map[int32]string{
		0: "ALL_AT_ONCE",
		1: "CANARY",
		2: "PERCENTAGE",
	}
	RolloutStrategy_value = map[string]int32{
		"ALL_AT_ONCE": 0,
		"CANARY":      1,
		"PERCENTAGE":  2,
	}
)

func (x RolloutStrategy) Enum() *RolloutStrategy {
	p := new(RolloutStrategy)
	*p = x
	return p
}

func (x RolloutStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (RolloutStrategy) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x RolloutStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutStrategy.Descriptor instead.
func (RolloutStrategy) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

// Rollout status
type RolloutStatus int32

const (
	RolloutStatus_PENDING     RolloutStatus = 0
	RolloutStatus_IN_PROGRESS RolloutStatus = 1
	RolloutStatus_COMPLETED   RolloutStatus = 2
	RolloutStatus_FAILED      RolloutStatus = 3
	RolloutStatus_ROLLED_BACK RolloutStatus = 4
)

// Enum value maps for RolloutStatus.
var (
	RolloutStatus_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "COMPLETED",
		3: "FAILED",
		4: "ROLLED_BACK",
	}
	RolloutStatus_value = map[string]int32{
		"PENDING":     0,
		"IN_PROGRESS": 1,
		"COMPLETED":   2,
		"FAILED":      3,
		"ROLLED_BACK": 4,
	}
)

func (x RolloutStatus) Enum() *RolloutStatus {
	p := new(RolloutStatus)
	*p = x
	return p
}

func (x RolloutStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (RolloutStatus) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x RolloutStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutStatus.Descriptor instead.
func (RolloutStatus) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

// Health status
type HealthStatus int32

const (
	HealthStatus_HEALTHY   HealthStatus = 0
	HealthStatus_DEGRADED  HealthStatus = 1
	HealthStatus_UNHEALTHY HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTHY",
		1: "DEGRADED",
		2: "UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTHY":   0,
		"DEGRADED":  1,
		"UNHEALTHY": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

// Configuration data structure
type ConfigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`          // Unique identifier (e.g., "app-config-v3")
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Target service name
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                           // Version number
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                            // Actual config content (JSON/YAML/TOML)
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`                              // Format: "json", "yaml", "toml"
	ContentHash   string                 `protobuf:"bytes,6,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // SHA256 hash for integrity
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // Unix timestamp
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`       // User/system that created it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigData) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ConfigData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigData) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigData) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ConfigData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ConfigData) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// Configuration metadata (stored in PostgreSQL)
type ConfigMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMetadata) Reset() {
	*x = ConfigMetadata{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMetadata) ProtoMessage() {}

func (x *ConfigMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMetadata.ProtoReflect.Descriptor instead.
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigMetadata) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ConfigMetadata) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ConfigMetadata) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ConfigMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigMetadata) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// Rollout state
type RolloutState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigId          string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Strategy          RolloutStrategy        `protobuf:"varint,2,opt,name=strategy,proto3,enum=configservice.RolloutStrategy" json:"strategy,omitempty"`
	TargetPercentage  int32                  `protobuf:"varint,3,opt,name=target_percentage,json=targetPercentage,proto3" json:"target_percentage,omitempty"`    // Target percentage (0-100)
	CurrentPercentage int32                  `protobuf:"varint,4,opt,name=current_percentage,json=currentPercentage,proto3" json:"current_percentage,omitempty"` // Current rollout percentage
	Status            RolloutStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=configservice.RolloutStatus" json:"status,omitempty"`
	StartedAt         int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt       int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RolloutState) Reset() {
	*x = RolloutState{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutState) ProtoMessage() {}

func (x *RolloutState) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutState.ProtoReflect.Descriptor instead.
func (*RolloutState) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *RolloutState) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *RolloutState) GetStrategy() RolloutStrategy {
	if x != nil {
		return x.Strategy
	}
	return RolloutStrategy_ALL_AT_ONCE
}

func (x *RolloutState) GetTargetPercentage() int32 {
	if x != nil {
		return x.TargetPercentage
	}
	return 0
}

func (x *RolloutState) GetCurrentPercentage() int32 {
	if x != nil {
		return x.CurrentPercentage
	}
	return 0
}

func (x *RolloutState) GetStatus() RolloutStatus {
	if x != nil {
		return x.Status
	}
	return RolloutStatus_PENDING
}

func (x *RolloutState) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *RolloutState) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

// Service instance information
type ServiceInstance struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServiceName          string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId           string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Unique instance identifier
	CurrentConfigVersion int64                  `protobuf:"varint,3,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	LastHeartbeat        int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Status               string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                                                               // "connected", "disconnected", "unhealthy"
	Metadata             map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional instance info
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceInstance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServiceInstance) GetCurrentConfigVersion() int64 {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return 0
}

func (x *ServiceInstance) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ServiceInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInstance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Health report from service instance
type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ConfigVersion int64                  `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Status        HealthStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=configservice.HealthStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *HealthReport) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthReport) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HealthReport) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *HealthReport) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTHY
}

func (x *HealthReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HealthReport) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HealthReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\rconfigservice\"\xf9\x01\n" +
	"\n" +
	"ConfigData\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12!\n" +
	"\fcontent_hash\x18\x06 \x01(\tR\vcontentHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\"\xff\x01\n" +
	"\x0eConfigMetadata\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"\xbb\x02\n" +
	"\fRolloutState\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12:\n" +
	"\bstrategy\x18\x02 \x01(\x0e2\x1e.configservice.RolloutStrategyR\bstrategy\x12+\n" +
	"\x11target_percentage\x18\x03 \x01(\x05R\x10targetPercentage\x12-\n" +
	"\x12current_percentage\x18\x04 \x01(\x05R\x11currentPercentage\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.configservice.RolloutStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\"\xd1\x02\n" +
	"\x0fServiceInstance\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x16current_config_version\x18\x03 \x01(\x03R\x14currentConfigVersion\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.configservice.ServiceInstance.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x02\n" +
	"\fHealthReport\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x03R\rconfigVersion\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.configservice.HealthStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12B\n" +
	"\ametrics\x18\x06 \x03(\v2(.configservice.HealthReport.MetricsEntryR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*>\n" +
	"\x0fRolloutStrategy\x12\x0f\n" +
	"\vALL_AT_ONCE\x10\x00\x12\n" +
	"\n" +
	"\x06CANARY\x10\x01\x12\x0e\n" +
	"\n" +
	"PERCENTAGE\x10\x02*Y\n" +
	"\rRolloutStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\x0f\n" +
	"\vROLLED_BACK\x10\x04*8\n" +
	"\fHealthStatus\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\f\n" +
	"\bDEGRADED\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02B#Z!github.com/codec404/Konfig/pkg/pbb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_config_proto_goTypes = []any{
	(RolloutStrategy)(0),    // 0: configservice.RolloutStrategy
	(RolloutStatus)(0),      // 1: configservice.RolloutStatus
	(HealthStatus)(0),       // 2: configservice.HealthStatus
	(*ConfigData)(nil),      // 3: configservice.ConfigData
	(*ConfigMetadata)(nil),  // 4: configservice.ConfigMetadata
	(*RolloutState)(nil),    // 5: configservice.RolloutState
	(*ServiceInstance)(nil), // 6: configservice.ServiceInstance
	(*HealthReport)(nil),    // 7: configservice.HealthReport
	nil,                     // 8: configservice.ServiceInstance.MetadataEntry
	nil,                     // 9: configservice.HealthReport.MetricsEntry
}
var file_config_proto_depIdxs = []int32{
	0, // 0: configservice.RolloutState.strategy:type_name -> configservice.RolloutStrategy
	1, // 1: configservice.RolloutState.status:type_name -> configservice.RolloutStatus
	8, // 2: configservice.ServiceInstance.metadata:type_name -> configservice.ServiceInstance.MetadataEntry
	2, // 3: configservice.HealthReport.status:type_name -> configservice.HealthStatus
	9, // 4: configservice.HealthReport.metrics:type_name -> configservice.HealthReport.MetricsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
