// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: distribution.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_NEW_CONFIG     UpdateType = 0 // Brand new config
	UpdateType_VERSION_UPDATE UpdateType = 1 // Version change
	UpdateType_ROLLBACK       UpdateType = 2 // Rollback to previous version
	UpdateType_HEARTBEAT_ACK  UpdateType = 3 // Acknowledgment of heartbeat
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "NEW_CONFIG",
		1: "VERSION_UPDATE",
		2: "ROLLBACK",
		3: "HEARTBEAT_ACK",
	}
	UpdateType_value = map[string]int32{
		"NEW_CONFIG":     0,
		"VERSION_UPDATE": 1,
		"ROLLBACK":       2,
		"HEARTBEAT_ACK":  3,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_distribution_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_distribution_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{0}
}

// Subscribe request from client
type SubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId     string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                                     // Unique instance ID
	CurrentVersion int64                  `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`                                        // Current config version (0 if none)
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Instance metadata (hostname, etc.)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_distribution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SubscribeRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *SubscribeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Config update pushed to client
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigData            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ForceReload   bool                   `protobuf:"varint,2,opt,name=force_reload,json=forceReload,proto3" json:"force_reload,omitempty"` // Force immediate reload
	UpdateType    UpdateType             `protobuf:"varint,3,opt,name=update_type,json=updateType,proto3,enum=configservice.UpdateType" json:"update_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_distribution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigUpdate) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigUpdate) GetForceReload() bool {
	if x != nil {
		return x.ForceReload
	}
	return false
}

func (x *ConfigUpdate) GetUpdateType() UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return UpdateType_NEW_CONFIG
}

// Health acknowledgment
type HealthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthAck) Reset() {
	*x = HealthAck{}
	mi := &file_distribution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAck) ProtoMessage() {}

func (x *HealthAck) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAck.ProtoReflect.Descriptor instead.
func (*HealthAck) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{2}
}

func (x *HealthAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *HealthAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_distribution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Alive           bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_distribution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

var File_distribution_proto protoreflect.FileDescriptor

const file_distribution_proto_rawDesc = "" +
	"\n" +
	"\x12distribution.proto\x12\rconfigservice\x1a\fconfig.proto\"\x87\x02\n" +
	"\x10SubscribeRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\x03R\x0ecurrentVersion\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.configservice.SubscribeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\fConfigUpdate\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.configservice.ConfigDataR\x06config\x12!\n" +
	"\fforce_reload\x18\x02 \x01(\bR\vforceReload\x12:\n" +
	"\vupdate_type\x18\x03 \x01(\x0e2\x19.configservice.UpdateTypeR\n" +
	"updateType\"A\n" +
	"\tHealthAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"T\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp*Q\n" +
	"\n" +
	"UpdateType\x12\x0e\n" +
	"\n" +
	"NEW_CONFIG\x10\x00\x12\x12\n" +
	"\x0eVERSION_UPDATE\x10\x01\x12\f\n" +
	"\bROLLBACK\x10\x02\x12\x11\n" +
	"\rHEARTBEAT_ACK\x10\x032\xfb\x01\n" +
	"\x13DistributionService\x12M\n" +
	"\tSubscribe\x12\x1f.configservice.SubscribeRequest\x1a\x1b.configservice.ConfigUpdate(\x010\x01\x12E\n" +
	"\fReportHealth\x12\x1b.configservice.HealthReport\x1a\x18.configservice.HealthAck\x12N\n" +
	"\tHeartbeat\x12\x1f.configservice.HeartbeatRequest\x1a .configservice.HeartbeatResponseB#Z!github.com/codec404/Konfig/pkg/pbb\x06proto3"

var (
	file_distribution_proto_rawDescOnce sync.Once
	file_distribution_proto_rawDescData []byte
)

func file_distribution_proto_rawDescGZIP() []byte {
	file_distribution_proto_rawDescOnce.Do(func() {
		file_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distribution_proto_rawDesc), len(file_distribution_proto_rawDesc)))
	})
	return file_distribution_proto_rawDescData
}

var file_distribution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_distribution_proto_goTypes = []any{
	(UpdateType)(0),           // 0: configservice.UpdateType
	(*SubscribeRequest)(nil),  // 1: configservice.SubscribeRequest
	(*ConfigUpdate)(nil),      // 2: configservice.ConfigUpdate
	(*HealthAck)(nil),         // 3: configservice.HealthAck
	(*HeartbeatRequest)(nil),  // 4: configservice.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 5: configservice.HeartbeatResponse
	nil,                       // 6: configservice.SubscribeRequest.MetadataEntry
	(*ConfigData)(nil),        // 7: configservice.ConfigData
	(*HealthReport)(nil),      // 8: configservice.HealthReport
}
var file_distribution_proto_depIdxs = []int32{
	6, // 0: configservice.SubscribeRequest.metadata:type_name -> configservice.SubscribeRequest.MetadataEntry
	7, // 1: configservice.ConfigUpdate.config:type_name -> configservice.ConfigData
	0, // 2: configservice.ConfigUpdate.update_type:type_name -> configservice.UpdateType
	1, // 3: configservice.DistributionService.Subscribe:input_type -> configservice.SubscribeRequest
	8, // 4: configservice.DistributionService.ReportHealth:input_type -> configservice.HealthReport
	4, // 5: configservice.DistributionService.Heartbeat:input_type -> configservice.HeartbeatRequest
	2, // 6: configservice.DistributionService.Subscribe:output_type -> configservice.ConfigUpdate
	3, // 7: configservice.DistributionService.ReportHealth:output_type -> configservice.HealthAck
	5, // 8: configservice.DistributionService.Heartbeat:output_type -> configservice.HeartbeatResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_distribution_proto_init() }
func file_distribution_proto_init() {
	if File_distribution_proto != nil {
		return
	}
	file_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distribution_proto_rawDesc), len(file_distribution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distribution_proto_goTypes,
		DependencyIndexes: file_distribution_proto_depIdxs,
		EnumInfos:         file_distribution_proto_enumTypes,
		MessageInfos:      file_distribution_proto_msgTypes,
	}.Build()
	File_distribution_proto = out.File
	file_distribution_proto_goTypes = nil
	file_distribution_proto_depIdxs = nil
}
